### ISSUE TITLE
Ep 24 - Self-Programming and Bootloaders

### ISSUE THREAD

**Issue by embeddedshiv** [MicrochipTech/avr_insights#1]
**Description**
The download page includes a link to several examples for getting started with the AVR using Atmel start.
I am more interested in the Ep 24 - Self-Programming and Bootloaders.

**Checklist:**
- [ ] How do I get documents & related video tutorials for Ep 24 - Self-Programming and Bootloaders?

**Comment by Martin-MCHP** [comment]
Hi,

Currently there is no code directly related t Ep 24, but I have some useful links to app notes and code. 

Newer devices:
[AN2634 - Bootloader-for-tinyAVR-and-megaAVR](https://www.microchip.com//wwwAppNotes/AppNotes.aspx?appnote=en604508)
[AN3341 - Basic Bootloader for the AVR-DA Family](https://www.microchip.com/wwwappnotes/appnotes.aspx?appnote=en1001654)

Older devices:
[AVR109: Using Self Programming on tinyAVR and megaAVR devices](https://www.microchip.com//wwwAppNotes/AppNotes.aspx?appnote=en591230)
[AVR230: DES Bootloader on tinyAVR and megaAVR devices](https://www.microchip.com//wwwAppNotes/AppNotes.aspx?appnote=en591504)

Hope this helps. 

Best regards
Martin

**Comment by Dradnats** [comment]
@embeddedshiv,
Closing this issue. Hope the resources provided have been helpful.
Best Regards,
Martin
